spring:
  application:
    name: 'eureka-service'

server:
  port: 4400

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:4400/eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
